### ISSUE TITLE
Weird curve from 'Extract centerline'

### ISSUE THREAD

**Issue by chir-set** [vmtk/SlicerExtension-VMTK#88] opened 2023-07-14 18:30 UTC
Hi all,

I just noticed a weird curve produced by 'Extract centerline' module with Slicer Preview 5.3.0-2023-07-10 r31866 / e757858. No problem occurs with Slicer Stable.

![Preview1-20230710](https://github.com/vmtk/SlicerExtension-VMTK/assets/33979252/5b33e065-28d9-4ec6-ab54-d4ee9bdd6609)

![Preview2-20230710](https://github.com/vmtk/SlicerExtension-VMTK/assets/33979252/679b07bf-22a2-49c4-a660-1ccb6b44f5ec)

FYI.

Regards.

@lassoan

**Comment by lassoan** [comment] 2023-07-14 18:36
Please attach in a zip file the model and the endpoints markup files so that we can reproduce the issue.

**Comment by chir-set** [comment] 2023-07-14 18:50
Here it is. The source volume is CTA-cardio.

[WeirdCenterlineCurve.mrb.zip](https://github.com/vmtk/SlicerExtension-VMTK/files/12053146/WeirdCenterlineCurve.mrb.zip)

Thanks.

**Comment by HenriGiroussens** [comment] 2023-10-05 14:22
I have the same problem.
The problem is that if you have a curve with N points, the points order is [2, 3, ...,N-1, N, 1] instead of [1, 2, ..., N-1, N].
The origin point is in position N, or N-1.

Here is some prints of my curve coordinates:
0 (-27.201675415039062, 187.16107177734375, -890.1677856445312)
1 (-26.9527530670166, 187.3804931640625, -891.1237182617188)
2 (-26.722936630249023, 187.3258056640625, -892.1171264648438)
3 (-26.452434539794922, 187.4422149658203, -893.0775146484375)
4 (-26.237762451171875, 187.5565185546875, -894.0722045898438)
5 (-25.979354858398438, 187.46963500976562, -895.0490112304688)
6 (-25.859407424926758, 187.419189453125, -896.0513305664062)
7 (-25.78296661376953, 187.21885681152344, -897.037353515625)
8 (-25.569198608398438, 187.07861328125, -898.0177612304688)
9 (-25.386798858642578, 186.76638793945312, -898.9619750976562)
10 (-24.98750114440918, 186.5948486328125, -899.8720703125)
11 (-24.516298294067383, 186.50828552246094, -900.7686157226562)
12 (-23.979717254638672, 186.5306854248047, -901.5891723632812)
13 (-23.38378143310547, 186.5390167236328, -902.42529296875)
14 (-22.740461349487305, 186.71588134765625, -903.1613159179688)
15 (-22.11358642578125, 186.80291748046875, -903.9608154296875)
16 (-21.53929328918457, 186.80775451660156, -904.8031005859375)
17 (-20.978464126586914, 186.92723083496094, -905.6372680664062)
18 (-20.625045776367188, 186.84939575195312, -906.5939331054688)
19 (-20.107505798339844, 186.77195739746094, -907.4588012695312)
20 (-19.493471145629883, 186.54165649414062, -908.2208862304688)
21 (-18.840431213378906, 186.48828125, -908.9989013671875)
22 (-18.240644454956055, 186.3766326904297, -909.8034057617188)
23 (-17.672645568847656, 186.3932647705078, -910.6463623046875)
24 (-17.100486755371094, 186.30859375, -911.455078125)
25 (-16.419158935546875, 186.07638549804688, -912.1573486328125)
26 (-15.820740699768066, 186.14199829101562, -912.970458984375)
27 (-15.075986862182617, 185.98538208007812, -913.6253662109375)
28 (-14.322989463806152, 186.1002197265625, -914.3040771484375)
29 (-13.654383659362793, 185.8844757080078, -915.0823364257812)
30 (-13.352336883544922, 185.9193878173828, -916.022216796875)
31 (-12.896366119384766, 185.74964904785156, -916.9221801757812)
32 (-12.433988571166992, 185.9099578857422, -917.8152465820312)
33 (-11.876144409179688, 185.8268280029297, -918.6508178710938)
34 (-11.319369316101074, 185.724609375, -919.4981079101562)
35 (-10.648343086242676, 185.82427978515625, -920.2484741210938)
36 (-10.289870262145996, 185.6748809814453, -921.189208984375)
37 (-9.872958183288574, 185.7279052734375, -922.1102294921875)
38 (-9.555660247802734, 185.75205993652344, -923.0731811523438)
39 (-9.129727363586426, 185.65164184570312, -923.9856567382812)
40 (-8.781815528869629, 185.57485961914062, -924.931640625)
41 (-8.430359840393066, 185.4058380126953, -925.8724365234375)
42 (-8.06764030456543, 185.29373168945312, -926.8164672851562)
43 (-7.7473907470703125, 185.0701141357422, -927.7506713867188)
44 (-7.370983123779297, 184.94253540039062, -928.6857299804688)
45 (-6.984907627105713, 184.88320922851562, -929.622802734375)
46 (-6.585989952087402, 184.84193420410156, -930.544921875)
47 (-6.0658464431762695, 185.00344848632812, -931.4163818359375)
48 (-5.701124668121338, 184.86294555664062, -932.3291625976562)
49 (-27.67124366760254, 186.95880126953125, -888.52685546875)
50 (-5.375463962554932, 184.77696228027344, -933.1472778320312)


0 (-5.652944087982178, 185.62625122070312, -934.5128173828125)
1 (-5.557351112365723, 185.9490966796875, -935.4443969726562)
2 (-5.423030376434326, 186.07302856445312, -936.4557495117188)
3 (-4.962557792663574, 186.2572021484375, -937.3352661132812)
4 (-4.707637786865234, 186.08224487304688, -938.2938842773438)
5 (-4.252084732055664, 185.9478302001953, -939.187744140625)
6 (-4.008609294891357, 185.92669677734375, -940.1653442382812)
7 (-3.6661746501922607, 185.83949279785156, -941.1022338867188)
8 (-3.3224732875823975, 185.9415283203125, -942.0359497070312)
9 (-3.0320496559143066, 185.94871520996094, -943.0033569335938)
10 (-2.652219295501709, 185.89707946777344, -943.94140625)
11 (-2.2956037521362305, 185.99867248535156, -944.8810424804688)
12 (-1.9806890487670898, 185.99668884277344, -945.833251953125)
13 (-1.742680549621582, 185.89649963378906, -946.8040161132812)
14 (-1.515800952911377, 186.05918884277344, -947.7744140625)
15 (-1.3741973638534546, 186.12159729003906, -948.7789306640625)
16 (-1.3706382513046265, 186.40586853027344, -949.74658203125)
17 (-1.5049915313720703, 186.54519653320312, -950.7283935546875)
18 (-1.7887212038040161, 186.7136993408203, -951.6857299804688)
19 (-2.2207419872283936, 186.93966674804688, -952.556640625)
20 (-2.7864339351654053, 187.37338256835938, -953.26904296875)
21 (-3.424830675125122, 187.7100372314453, -953.9651489257812)
22 (-4.165303707122803, 188.07009887695312, -954.5585327148438)
23 (-5.012478351593018, 188.47769165039062, -954.9566040039062)
24 (-5.900235652923584, 188.85919189453125, -955.2230224609375)
25 (-6.819647789001465, 189.20094299316406, -955.45654296875)
26 (-7.716747283935547, 189.6412353515625, -955.5464477539062)
27 (-8.645044326782227, 190.0144805908203, -955.4715576171875)
28 (-9.615845680236816, 190.24378967285156, -955.375732421875)
29 (-10.491643905639648, 190.65252685546875, -955.0831909179688)
30 (-11.416428565979004, 190.9860382080078, -954.85986328125)
31 (-12.247751235961914, 191.4864959716797, -954.559814453125)
32 (-13.137051582336426, 191.71441650390625, -954.183349609375)
33 (-14.060540199279785, 192.06121826171875, -953.9885864257812)
34 (-15.024733543395996, 192.25914001464844, -953.86572265625)
35 (-16.00592803955078, 192.34825134277344, -953.88623046875)
36 (-16.97979164123535, 192.46795654296875, -954.0929565429688)
37 (-17.947154998779297, 192.45777893066406, -954.3637084960938)
38 (-18.859861373901367, 192.59178161621094, -954.7254638671875)
39 (-19.76064109802246, 192.6469268798828, -955.1796264648438)
40 (-20.624998092651367, 192.6896209716797, -955.6910400390625)
41 (-21.466365814208984, 192.75881958007812, -956.2415161132812)
42 (-22.318256378173828, 192.76564025878906, -956.7601928710938)
43 (-23.23590660095215, 192.80604553222656, -957.1375732421875)
44 (-24.121307373046875, 192.7863006591797, -957.5963134765625)
45 (-24.988237380981445, 192.718994140625, -958.1253662109375)
46 (-25.851457595825195, 192.57460021972656, -958.6110229492188)
47 (-26.732389450073242, 192.6102752685547, -959.0952758789062)
48 (-27.684358596801758, 192.70120239257812, -959.3855590820312)
49 (-28.66575050354004, 192.77259826660156, -959.5634765625)
50 (-29.66434097290039, 192.64376831054688, -959.554931640625)
51 (-30.640941619873047, 192.84930419921875, -959.422607421875)
52 (-31.625246047973633, 192.93080139160156, -959.3338012695312)
53 (-32.60881805419922, 193.09059143066406, -959.447998046875)
54 (-5.375463962554932, 184.77696228027344, -933.1472778320312)


How to reproduce:
Use the extract centerline module on a binary mask, with autodetect endpoints, with centerline curve parameter sur to "Create new Curve". All other parameters to default.

Version: Slicer 5.4 with latest SlicerVMTK.

I looked into the code, the problem seems to comes from the vmtk C++ lib

**Comment by lassoan** [comment] 2024-03-30 19:21
Fixed in https://github.com/vmtk/SlicerExtension-VMTK/pull/106

**Closed by lassoan** 2024-03-30 19:21 UTC
